### ISSUE TITLE
Cinsiyet doğrulama

### ISSUE THREAD

**Issue by bhdrnzl** [epigra/tckimlik#9]
Bu paket ile cinsiyet doğrulama nasıl yapabilirim? örneğin siteye sadece erkeklerin kayıt olmasını istiyorum. Bunu nasıl yapabilirim?

teşekkür ederim.

**Comment by jnbn** [comment]
Merhaba,

TCKimlik doğrulama servisinde böyle biz özellik bulunmadığı için; cinsiyete dayalı bir doğrulama yapabilmek ne yazık ki mümkün değil. Kullanıcı beyanı üzerinden gitmek haricinde bir yol -en azından ben- bilmiyorum.
